LMS Portal/learning/accounts/urls.py
from django.urls import path,include
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView

from .forms import *
from .views import *
from .forms import *
app_name = 'accounts'

urlpatterns = [
    
    #one for logout also!!
    path('',login, name='login'),
    path('register/', Register, name='register'),
    path('logout/', logout, name='logout'),
    
    path('coursedetail/<int:course_id>/',coursedetail, name='coursedetail'),
    path('contact/<int:stu_id>/',contact, name='contact'),
    path('contactsave',contactsave, name='contactsave'),
    path('stcontact', stcontact, name='stcontact'),

    path('activate/<uidb64>/<token>/',activate,name='activate'),

    path('reset_password/',
        PasswordResetView.as_view(template_name='password_reset.html',
            form_class=EmailValidationOnForgotPassword),name='password_reset'),

    path('password_reset/done/',
        PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
        name="password_reset_confirm"),

    path('reset/done/',
        PasswordResetCompleteView.as_view(template_name='password_reset_done.html'),
        name='password_reset_complete'),

    path('dashstu/', dashstu, name='dashstu'),
    path('dashteach/', dashteach, name='dashteach'),
    path('dashboard/', dashboard, name='dashboard'),
    path('quizteach/', quizteach, name='quizteach'),
    path('quizstu/', quizstu, name='quizstu'),
    path('addquestion/', addquestion, name='addquestion'),
    
]

LMS Portal/learning/chatbot/urls.py
s

LMS Portal/learning/courses/urls.py
from django.urls import path

from .views import *
app_name = 'courses'

urlpatterns = [
    path('allcourse',allcourse, name='allcourse'),
    path('addcourse',addcourse , name='addcourse'),
    path('addmaterial', addmaterial, name='addmaterial'),
    path('detail/<int:course_id>/', detail, name='detail'),
    path('enrollment/<int:course_id>/', enrollment, name='enrollment'),
    path('courmat/<int:course_id>/', courmat, name='courmat'),
    path('show/<int:file_id>/', show, name='show'),
    path('submit/<int:assign_id>/', submit, name='submit'),
    path('assignment/<int:assign_id>/', assignment, name='assignment'),
]

LMS Portal/learning/learning/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home, name='home'),
    path('contactus/',Contactus,name='contactus'),
    path('aboutus/',aboutUs,name='about'),
    path('', include('accounts.urls', namespace='accounts')),
    # path('chatbot/', include('chatbot.urls', namespace='chatbot')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('discussions/', include('discussions.urls', namespace='discussions')),
    path('quizzes/', include('quizzes.urls', namespace='quizzes')),
    path('leaderboard/', include('leaderboard.urls', namespace='leaderboard')),
    path('',include('django.contrib.auth.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS Portal/learning/quizzes/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "quizzes"

urlpatterns = [
    path('createAssignment/',createAssignment,name="cassgn"),
    path('quizhome/',QuizHome,name='qhome'),
    path('quizmain/',QuizMain,name='qmain'),
    path('submitAssignment/',submitAssignment,name='sassgn'),
    path('takequiz/<int:quiz_id>/', takequiz, name='takequiz'),
    path('storeresult', storeresult, name='storeresult'),
    path('addques/<int:quiz_id>/', addques, name='addques'),
    path('assignstu', assignstu, name='assignstu'),
]

LMS Portal/learning/quizzes/models.py
from django.db import models
from courses.models import *
from django.contrib.auth.models import User
#1 for creating assignment
from courses.models import Course


class CreateAssignment(models.Model):

	info = models.ForeignKey(Course,on_delete=models.CASCADE,null=True)
	created_on = models.DateTimeField()
	title = models.CharField(max_length=200,null=True,blank=False)
	desc = models.TextField(null=True,blank=False)
	task = models.FileField(null=True,blank=False)

	def __str__(self):
		return self.title+'-'+self.info.subject

	class Meta:
		verbose_name_plural = 'Create Assignment'

#for saving qiuz's data : Home Page - Quizhome
class CreateQuiz_1(models.Model):
	author = models.ForeignKey(User,on_delete=models.CASCADE,blank=True, null=True)
	info = models.ForeignKey(Course,on_delete=models.CASCADE,null=True)
	date = models.DateTimeField()
	title = models.CharField(max_length=200,null=True,blank=False)
	desc = models.TextField(null=True,blank=False)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name_plural = 'Quiz Home'

#for adding questions in this Quiz - Quizmain
class CreateQuiz_2(models.Model):
	
	CHOICES = (
		('A','Option A'),
		('B','Option B'),
		('C','Option C'),
		('D','Option D')
	)

	#data has been taken from the quiz home model.
	data = models.ForeignKey(CreateQuiz_1,on_delete=models.CASCADE,null=True)
	question = models.TextField(null=True,blank=False)
	option1 = models.TextField(null=True,blank=False)
	option2 = models.TextField(null=True,blank=False)
	option3 = models.TextField(null=True,blank=False)
	option4 = models.TextField(null=True,blank=False)
	answer = models.CharField(choices=CHOICES,max_length=1,null=True,blank=False)

	class Meta:
		verbose_name_plural = 'Quiz Main'


class SubmitAssignment(models.Model):
	course = models.ForeignKey(Course,on_delete=models.CASCADE, blank=True, null=True)
	data = models.ForeignKey(CreateAssignment,on_delete=models.CASCADE,null=True)
	studentResponse = models.FileField(null=True,blank=False)
	student = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	class Meta:
		verbose_name_plural = 'Submit Assignment'


class SubmitQuiz(models.Model):

	subject = models.ForeignKey(Course,on_delete=models.CASCADE,null = True)
	title = models.ForeignKey(CreateQuiz_1,on_delete=models.CASCADE,null = True)
	answer = models.CharField(max_length=20,null=True,blank=False)


class Exam(models.Model):
	quiz = models.ForeignKey(CreateQuiz_1,on_delete=models.CASCADE)
	ques = models.CharField(max_length=100)
	qno = models.IntegerField(blank=True, null=True)
	o1 = models.CharField(max_length=100)
	o2 = models.CharField(max_length=100)
	o3 = models.CharField(max_length=100)
	o4 = models.CharField(max_length=100)
	cans = models.CharField(max_length=100)

	def __str__(self):
		return self.quiz.title



class Result(models.Model):
	student = models.ForeignKey(User,on_delete=models.CASCADE, related_name='student')
	quiz = models.ForeignKey(CreateQuiz_1,on_delete=models.CASCADE)
	score = models.CharField(max_length=20)
	teach = models.ForeignKey(User,on_delete=models.CASCADE,related_name='teach', blank=True, null=True)

	def __str__(self):
		return self.student.username+" "+self.quiz.title

LMS Portal/learning/quizzes/views.py
from django.shortcuts import render, redirect
from .models import *
from courses.models import *
from django.contrib.auth.decorators import login_required
#Teacher's end for assignment creation.
@login_required
def createAssignment(request):
	if request.method == 'POST':
		CA = CreateAssignment()

		CA.info = Course.objects.filter(name=request.POST['info']).first()
		CA.created_on = request.POST.get('created_on')
		CA.title = request.POST['title']
		CA.desc = request.POST['desc']
		CA.task = request.FILES.get('task')
		CA.save()
		return render(request,'thanks.html',{
			'courses':Course.objects.all(),
			'message':'You have successfully created the assignment!'
			})
	else:
		return render(request,'createAssignment.html',{
				'courses':Course.objects.filter(author=request.user)
			})

# Home page for the quiz - complete
@login_required
def QuizHome(request):
	if request.method == 'POST':
		CQ1 = CreateQuiz_1()
		
		CQ1.date = request.POST.get('created_on')
		CQ1.title = request.POST['title']
		CQ1.desc = request.POST['desc']
		CQ1.data = Course.objects.filter(name = request.POST['info']).first()
		CQ1.author = request.user
		CQ1.save()
		return render(request,'quizHome.html',{
			'message':'Your Data has been saved successfully!! Now, You can Now Add problems!!'
			})
	else:
		return render(request,'quizHome.html',{
			'courses':Course.objects.all()
			})

#pass data successfully added message here.

#You need to link the user seeting the quiz!!  - !!ISSUE!!
@login_required
def QuizMain(request):
	if request.method == 'POST':
		CQ2 = CreateQuiz_2()
		if request.POST.get('save'):
			
			#CQ2.data = CreateQuiz_1.objects.filter(pk=reques.POST['quiz_id']).first()
			CQ2.question = request.POST['question']
			CQ2.option1 = request.POST['option1']
			CQ2.option2 = request.POST['option2']
			CQ2.option3 = request.POST['option3']
			CQ2.option4 = request.POST['option4']
			CQ2.answer = request.POST['answer']
			#CQ2.save()

			return render(request,'quizMain.html',{

				})

		elif request.POST.get('exit'):
			
			# CQ2.data = ??
			CQ2.question = request.POST['question']
			CQ2.option1 = request.POST['option1']
			CQ2.option2 = request.POST['option2']
			CQ2.option3 = request.POST['option3']
			CQ2.option4 = request.POST['option4']
			CQ2.answer = request.POST['answer']
			#CQ2.save()

			return render(request,'thanks.html',{
				'message':'You have successfully created the quiz!'
				})

	else:
		return render(request,'quizMain.html',{

			})
@login_required
def submitAssignment(request):
	return render(request,'submitAssignment.html',{})

@login_required
def takequiz(request, quiz_id):
	quiz = CreateQuiz_1.objects.filter(pk=quiz_id).first();
	question = Exam.objects.filter(quiz=quiz)
	return render(request, 'quiz.html',{'questions': question, 'quiz': quiz})
@login_required
def storeresult(request):
	res = Result()
	res.student = request.user
	quiz = CreateQuiz_1.objects.filter(pk=request.POST['quiz_id']).first()
	res.quiz =quiz
	teacher= quiz.info.author
	res.teach = teacher
	res.score = request.POST['score']
	res.save()
	return redirect('accounts:dashstu')
@login_required
def addques(request, quiz_id):
	print('HELLLLOOOOOO')
	if request.method == 'post':
		cc = Exam()
		quiz = CreateQuiz_1.objects.filter(pk=quiz_id).first()
		cc.quiz = quiz
		cc.qno = request.POST['qno']
		cc.ques = request.POST['ques']
		cc.o1 = request.POST['o1']
		cc.o2= request.POST['o2']
		cc.o3 = request.POST['o3']
		cc.o4 = request.POST['o4']
		cc.cans = request.POST['cans']
		cc.save()
	quiz = CreateQuiz_1.objects.filter(pk=quiz_id).first()
	return render(request, 'quizMain.html', {'quiz': quiz})


@login_required
def assignstu(request):
	# Get all courses the student is enrolled in
	enrolled_courses = Enroll.objects.filter(student=request.user).values_list('course', flat=True)
	
	# Get all assignments for these courses
	assignments = CreateAssignment.objects.filter(info__in=enrolled_courses)
	
	# Get submitted assignments
	submitted = SubmitAssignment.objects.filter(student=request.user)
	
	return render(request, 'assignstu.html', {
		'assign': submitted,
		'available_assignments': assignments
	})

LMS Portal/learning/quizzes/templates/assignstu.html
{% extends 'base.html' %}
{% block banner %}
<h1 class="text-white">
            Welcome back {{ request.user.username }}
          </h1>
          <p class="mx-auto text-white  mt-20 mb-40">
            Your Assignments
          </p>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="container">
        <!-- Available Assignments -->
        <div class="row mb-5">
            <div class="col-12">
                <div class="module">
                    <div class="module-head">
                        <h3>Available Assignments</h3>
                    </div>
                    <br><br>
                    <div class="module-body table">
                        <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">
                            <thead>
                                <tr>
                                    <th>Assignment Name</th>
                                    <th>Course</th>
                                    <th>Due Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for assignment in available_assignments %}
                                <tr class="odd gradeX">
                                    <td>{{ assignment.title }}</td>
                                    <td>{{ assignment.info.name }}</td>
                                    <td>{{ assignment.created_on }}</td>
                                    <td>
                                        <a href="{% url 'courses:assignment' assignment.id %}" class="btn btn-primary">View & Submit</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Submitted Assignments -->
        <div class="row">
            <div class="col-12">
                <div class="module">
                    <div class="module-head">
                        <h3>Submitted Assignments</h3>
                    </div>
                    <br><br>
                    <div class="module-body table">
                        <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped display" width="100%">
                            <thead>
                                <tr>
                                    <th>Assignment Name</th>
                                    <th>Course</th>
                                    <th>Submission Date</th>
                                    <th>Your Work</th>
                                    <th>Original Task</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for a in assign %}
                                <tr class="odd gradeX">
                                    <td>{{ a.data.title }}</td>
                                    <td>{{ a.data.info.name }}</td>
                                    <td>{{ a.data.created_on }}</td>
                                    <td>
                                        <a href="{{ a.studentResponse.url }}" class="btn btn-info">View Submission</a>
                                    </td>
                                    <td>
                                        <a href="{{ a.data.task.url }}" class="btn btn-secondary">View Task</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

LMS Portal/learning/quizzes/templates/assignteach.html
{% extends 'base.html' %}
{% block banner %}
<h1 class="text-white">
            Welcome back {{ request.user.username }}
          </h1>
          <p class="mx-auto text-white  mt-20 mb-40">
           Assignment
          </p>

{% endblock %}

{% block content %}


        <div class="wrapper">
            <div class="container">
                <div class="row">
                    <div class="span3">
                        <div class="sidebar">

                            <div class="module">
                                <div class="module-head">
                                    <h3>
                                        Assignment</h3>
                                </div>
                                <br><br>
                                <div class="module-body table">
                                    <table cellpadding="0" cellspacing="0" border="0" class="datatable-1 table table-bordered table-striped	 display"
                                        width="100%">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Assignment Name
                                                </th>
                                                <th>
                                                    Course
                                                </th>
                                                <th>
                                                    Student's name
                                                </th>
                                                <th>
                                                    Work
                                                </th>
                                                <th>
                                                    Contact
                                                </th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for a in assign %}
                                            <tr class="odd gradeX">
                                                <td>
                                                    {{ a.data.title }}
                                                </td>
                                                <td>
                                                    {{ a.data.info.name }}
                                                </td>

                                                <td class="center">
                                                   {{ a.student.username }}
                                                </td>
                                                <td class="center">
                                                    <a href="{{ a.studentresponse }}">{{ a.studentresponse }}</a>
                                                </td>
                                                 <td>
                                                     <a class="btn text-uppercase" href="{% url 'accounts:contact' q.student.id %}">Contact</a>
                                                 </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <!--/.module-->
                        </div>
                        <!--/.content-->
                    </div>
                    <!--/.span9-->
                </div>
            </div>
            <!--/.container-->
        </div>

{% endblock %}

LMS Portal/learning/quizzes/templates/createAssignment.html
{% extends 'base.html' %}
{% block banner %}
    <h1 class="card-header info-color white-text text-center py-4">
        <strong>Create Assignment</strong>
    </h1>
{% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="card">
        <h2 class="card-header info-color white-text text-center py-4">
            <strong>Create an Assignment</strong>
        </h2>
        <br><br>
        <div class="card-body px-lg-5 pt-0">
            <form action="{% url 'quizzes:cassgn' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group row">
                  <label for="disabledSelect" class="col-2 col-form-label">Subject</label>
                  <div class="col-10">
                  <select id="disabledSelect" class="form-control" name="info">
                    <option>Select Subject</option>
                    {% for course in courses %}
                        <option id="{{ course.id }}">{{ course.name }}</option>
                    {% endfor %}
                  </select>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="example-datetime-local-input" class="col-2 col-form-label">Date and time</label>
                  <div class="col-10">
                    <input class="form-control" type="datetime-local" value="YYYY-MM-DDTHH:MM:SS" id="example-datetime-local-input" name="created_on" required>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="example-text-input" class="col-2 col-form-label">Title</label>
                  <div class="col-10">
                    <input class="form-control" type="text" placeholder="Enter the title" id="example-text-input" name="title" required>
                  </div>
                </div>

                <div class="form-group">
                    <label for="exampleTextarea">Description</label>
                    <textarea class="form-control" id="exampleTextarea" rows="3" name="desc" placeholder="Enter the description of the assignment"></textarea>
                </div>

                <div class="form-group">
                    <label for="exampleInputFile">Assignment File</label>
                    <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp" name="task">
                    <small id="fileHelp" class="form-text text-muted">Give the assignment here.</small>
                </div>

                <button class="btn btn-rounded btn-success btn-block z-depth-0 my-4 waves-effect" type="submit">Assign</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

LMS Portal/learning/quizzes/templates/quiz.html
{% extends 'base.html' %}
{% block head %}
<script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js">
    </script>
<script>
    function getanswers()
    {

    var e=document.getElementsByTagName("input");
    var s=0;
    for(i=0;i<e.length;i++)
    {
    if(e[i].type=="radio")
        {

            if(e[i].checked)
            {
                var s1=e[i].value;
                var s2=e[i+1].value;

                if(s1.localeCompare(s2)==0)
                {

                s=s+1;
                }
            }
        }
    }


    document.getElementById("score").value = s;
    }
</script>


{% endblock %}
{% block banner %}
    <h1 class="card-header info-color white-text text-center py-4">
        <strong>Quiz Time</strong>
    </h1>
{% endblock %}
{% block content %}
<br><br><br>

<script>
    $(document).
</script>
<div class="container">
    <h1 style="text-align:center;font-family:Times New Roman"> {{ quiz.title }} Quiz</h1>
    <br><br><br>
    {% for q in questions %}
    <table>
        <tr>
            <td><h3 style="color:green">{{ q.ques }} ?</h3></td>
        </tr>
        <tr>
            <td><input type="radio" class="rb" name="{{ q.qno }}" id="o1" value="{{ q.o1 }}"> {{ q.o1 }} </td>
            <td><input type="text" hidden value="{{ q.cans }}"></td>
        </tr>
        <tr>
            <td><input type="radio" class="rb" name="{{ q.qno }}" id="o2" value="{{ q.o2 }}"> {{ q.o2 }} </td>
            <td><input type="text" hidden value="{{ q.cans }}"></td>
        </tr>
        <tr>
            <td><input type="radio" class="rb" name="{{ q.qno }}" id="o3" value="{{ q.o3 }}"> {{ q.o3 }} </td>
            <td><input type="text" hidden value="{{ q.cans }}"></td>
        </tr>
        <tr>
            <td><input type="radio" class="rb" id="o4" name="{{ q.qno }}" value="{{ q.o4 }}"> {{ q.o4 }} </td>
            <td><input type="text" hidden value="{{ q.cans }}"></td>
        </tr>
        <tr>
            <td><label id="cans" class="rb" style="display:none; color: green"><b>{{ q.cans }}</b></label></td>
        </tr>
    </table>
    <hr>
    {% endfor %}
    <div class="col-md-4">
    <input type="submit" class="btn btn-block btn-outline btn-success" value="Completed" id="but1" onclick="getanswers()"/>

        <br><br>
    <form action="{% url 'quizzes:storeresult' %}" method="POST">
        {% csrf_token %}
        <input type="text" hidden name="score" value="" id="score">
        <input type="text" hidden name="quiz_id" value="{{ quiz.id }}">
        <input type="submit" class="btn btn-block btn-outline btn-primary" value="SUBMIT TEST">
    </form>
    </div>
</div>
{% endblock %}

LMS Portal/learning/quizzes/templates/quizHome.html
{% extends 'base.html' %}
{% block banner %}
    <h1 class="card-header info-color white-text text-center py-4">
        <strong>Create Quiz</strong>
    </h1>
{% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="container">
        <h2 class="card-header info-color white-text text-center py-4">
            <strong>Create a Quiz</strong>
        </h2><br>
        {% if message %}
          <h2 class="card-header info-color text-center py-4">
            <strong style="color: green;">{{ message }}</strong>
          </h2><br><br>
          <button class="btn btn-rounded btn-primary btn-block z-depth-0 my-4 waves-effect" type="button"><a href="{% url 'quizzes:qmain' %}" style="color: white;">+ Add Questions to the Quiz</a></button>
        {% endif %}
        <br><br>
        <div class="card-body px-lg-5 pt-0">
            <form action="{% url 'quizzes:qhome' %}" method="post" >
                {% csrf_token %}

                <div class="form-group row">
                  <label for="disabledSelect" class="col-2 col-form-label">Subject</label>
                  <div class="col-10">
                  <select id="disabledSelect" class="form-control" name="info">
                    <option>Select Subject</option>
                    {% for course in courses %}
                        <option id="{{ course.id }}">{{ course.name }}</option>
                    {% endfor %}
                  </select>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="example-datetime-local-input" class="col-2 col-form-label">Date and time</label>
                  <div class="col-10">
                    <input class="form-control" type="datetime-local" value="YYYY-MM-DDTHH:MM:SS" id="example-datetime-local-input" name="created_on" required>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="example-text-input" class="col-2 col-form-label">Title</label>
                  <div class="col-10">
                    <input class="form-control" type="text" placeholder="Enter the title" id="example-text-input" name="title" required>
                  </div>
                </div>

                <div class="form-group">
                    <label for="exampleTextarea">Description</label>
                    <textarea class="form-control" id="exampleTextarea" rows="3" name="desc" placeholder="Enter the description of the assignment"></textarea>
                </div>

                <button class="btn btn-rounded btn-success btn-block z-depth-0 my-4 waves-effect" type="submit">Save</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

LMS Portal/learning/quizzes/templates/quizMain.html
{% extends 'base.html' %}
{% block banner %}
    <h1 class="card-header info-color white-text text-center py-4">
        <strong>Add Questions</strong>
    </h1>
{% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="container">
        <h2 class="card-header info-color white-text text-center py-4">
            <strong>Question</strong>
        </h2>


        <br><br>
        <div class="card-body px-lg-5 pt-0">
            <form action="{% url 'quizzes:addques' quiz.id %}" method="post" >
                {% csrf_token %}
                <div class="form-group row">
                  <label for="qnumber" class="col-2 col-form-label">Question No.</label>
                  <div class="col-10">
                    <textarea class="form-control" id="qnumber" rows="2" name="qno" placeholder="Question no" required></textarea>
                  </div>
                </div>
                <div class="form-group">
                    <label for="exampleTextarea">Question</label>
                    <textarea class="form-control" id="exampleTextarea" rows="3" name="ques" placeholder="Your Question Goes Here" required></textarea>
                </div>

                <div class="form-group row">
                  <label for="exampleTextarea1" class="col-2 col-form-label">Option A</label>
                  <div class="col-10">
                  <textarea class="form-control" id="exampleTextarea1" rows="2" name="o1" placeholder="Option A" required></textarea>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="exampleTextarea2" class="col-2 col-form-label">Option B</label>
                  <div class="col-10">
                    <textarea class="form-control" id="exampleTextarea2" rows="2" name="o2" placeholder="Option B" required></textarea>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="exampleTextarea3" class="col-2 col-form-label">Option C</label>
                  <div class="col-10">
                    <textarea class="form-control" id="exampleTextarea3" rows="2" name="o3" placeholder="Option C" required></textarea>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="exampleTextarea4" class="col-2 col-form-label">Option D</label>
                  <div class="col-10">
                    <textarea class="form-control" id="exampleTextarea4" rows="2" name="o4" placeholder="Option D" required></textarea>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="exampleTextarea5" class="col-2 col-form-label">Correct answer</label>
                  <div class="col-10">
                    <textarea class="form-control" id="exampleTextarea5" rows="2" name="cans" placeholder="Option D" required></textarea>
                  </div>
                </div>

                <button class="btn btn-rounded btn-primary btn-block z-depth-0 my-4 waves-effect" type="submit" name="save" value="save">Save and Add Another</button>


            </form>
        </div>
    </div>
</div>
{% endblock %}

LMS Portal/learning/quizzes/templates/submitAssignment.html
Thank You!!

LMS Portal/learning/quizzes/templates/thanks.html
{% extends 'base.html' %}
{% block banner %}
    <h1 class="card-header info-color white-text text-center py-4">
        <strong>Thank You for Contributing</strong>
    </h1>
{% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="card">
        <h2 class="card-header info-color text-center py-4">
            <strong style="color: green;">{{ message }}</strong>
        </h2>
    </div>    
</div>
{% endblock %}